//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRepair
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderCar()
        {
            this.RepeatHistories = new HashSet<RepeatHistory>();
            this.ScheduleStaffs = new HashSet<ScheduleStaff>();
        }
    
        public int ID_Order { get; set; }
        public int Status_ID { get; set; }
        public string ListOfWorks { get; set; }
        public decimal TotalPrice { get; set; }
        public int SpareParts_ID { get; set; }
        public string DateRequest { get; set; }
        public int STO_ID { get; set; }
        public Nullable<int> Car_ID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual SparePart SparePart { get; set; }
        public virtual StatusCar StatusCar { get; set; }
        public virtual STO STO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepeatHistory> RepeatHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleStaff> ScheduleStaffs { get; set; }
    }
}
