//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRepair
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.RepeatHistories = new HashSet<RepeatHistory>();
            this.ScheduleStaffs = new HashSet<ScheduleStaff>();
        }
    
        public int ID_Staff { get; set; }
        public string SurnameStaff { get; set; }
        public string NameSaff { get; set; }
        public string PatronymicStaff { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public int UserCredentials_ID { get; set; }
        public int Qualification_ID { get; set; }
    
        public virtual Qualification Qualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepeatHistory> RepeatHistories { get; set; }
        public virtual RoleStaff RoleStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleStaff> ScheduleStaffs { get; set; }
        public virtual UserCredential UserCredential { get; set; }
    }
}
