//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRepair
{
    using System;
    using System.Collections.Generic;
    
    public partial class STO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STO()
        {
            this.OrderCars = new HashSet<OrderCar>();
        }
    
        public int ID_STO { get; set; }
        public string AddressSTO { get; set; }
        public string ScheduleSTO { get; set; }
        public int AmountPlaces { get; set; }
        public string PhoneNumber { get; set; }
        public decimal ProfitSTO { get; set; }
        public int Workload_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCar> OrderCars { get; set; }
        public virtual WorkloadCar WorkloadCar { get; set; }
    }
}
